# Generated by Django 4.2.2 on 2023-06-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_migracion_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='isStaff',
            field=models.BooleanField(db_column='is_staff', default=False),
        ),
    ]
