"""creacion de tablas usuarios y publicaciones

Revision ID: 63b65a432907
Revises: 
Create Date: 2023-06-02 21:09:09.943517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b65a432907'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('apellido', sa.Text(), nullable=True),
    sa.Column('especialidad', sa.Text(), nullable=False),
    sa.Column('sexo', sa.Enum('MASCULINO', 'FEMENINO', 'OTRO', name='sexousuario'), nullable=False),
    sa.Column('celular', sa.Text(), nullable=True),
    sa.Column('consultorio', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('tipo_usuario', sa.Enum('ADMINISTRADOR', 'MEDICO', 'USUARIO', name='tipousuario'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('publicaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('habilitado', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicaciones')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
