"""cree tabla de usuarios

Revision ID: 72c0c16be59b
Revises: 
Create Date: 2023-05-25 21:17:29.761911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "72c0c16be59b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("apellido", sa.Text(), nullable=True),
        sa.Column("correo", sa.Text(), nullable=False),
        sa.Column("dni", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("correo"),
        sa.UniqueConstraint("dni"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usuarios")
    # ### end Alembic commands ###
