"""cree una nueva tabla mascotas

Revision ID: 84569d6c7bec
Revises: f2ab8f7ea814
Create Date: 2023-05-26 19:25:57.288670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84569d6c7bec'
down_revision = 'f2ab8f7ea814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('apellido', sa.Text(), nullable=True),
    sa.Column('sexo', sa.Enum('Macho', 'Hembra', 'Otro', name='sexoenum'), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('raza', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascotas')
    # ### end Alembic commands ###
