"""cree tabla de mascotas

Revision ID: f2ab8f7ea814
Revises: 72c0c16be59b
Create Date: 2023-05-25 23:03:26.854307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ab8f7ea814'
down_revision = '72c0c16be59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('usuarios_dni_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint('usuarios_dni_key', ['dni'])

    # ### end Alembic commands ###
